workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean & get packages
        script: |
          flutter clean
          flutter pub get

      - name: Build IPA (no codesign)
        script: |
          flutter build ipa --release --no-codesign
          echo "=== LIST build/ios ==="
          ls -la build/ios || true
          echo "=== LIST build/ios/ipa ==="
          ls -la build/ios/ipa || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
