workflows:
  ios-app:
    name: iOS App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS IPA (unsigned)
        script: flutter build ipa --release --no-codesign

      # 👇 استكشاف + نسخ ملف الـ IPA لمجلد artifacts بضمان
      - name: Collect IPA
        script: |
          echo "🔎 Listing build outputs..."
          ls -R build/ios || true
          echo "🔎 Searching for any .ipa file..."
          IPA_PATH=$(find build -name "*.ipa" | head -n1)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA found!" && exit 1
          fi
          echo "✅ Found IPA at: $IPA_PATH"
          mkdir -p artifacts
          cp "$IPA_PATH" artifacts/VAR-IPTV.ipa
          echo "📦 Copied to artifacts/VAR-IPTV.ipa"

    artifacts:
      - artifacts/VAR-IPTV.ipa
