workflows:
  ios-app:
    name: iOS App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      # 👇 نسخ GoogleService-Info.plist إلى مكانه
      - name: Copy GoogleService-Info.plist
        script: |
          echo "📂 نسخ GoogleService-Info.plist إلى Runner"
          cp ./ios/Runner/GoogleService-Info.plist $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Build iOS IPA (unsigned)
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
