workflows:
  ios-release-app-only:
    name: iOS Release - APP only (no signing)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: 3.35.4      # يطابق Dart ^3.5.3
      xcode: latest

    scripts:
      - name: Doctor & deps
        script: |
          flutter doctor -v
          flutter clean
          flutter pub get
          flutter precache --ios

      - name: Prepare CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      # ⬇️ بناء Release لجهاز حقيقي بدون توقيع — نأخذ .app من مجلد Products
      - name: Xcode build (no signing) → .app
        script: |
          set -e
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            IPHONEOS_DEPLOYMENT_TARGET=13.0

          echo "Listing build products:"
          ls -R build/Build/Products || true

    artifacts:
      # هذا هو مسار .app الناتج من خطوة build أعلاه
      - build/Build/Products/Release-iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
