workflows:
  ios-release-player:
    name: iOS Release Build - Player
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: 3.35.4   # <-- يطابق Dart ^3.5.3
      xcode: latest     # أو حدده إذا تحب (مثلاً 16.2)

    scripts:
      - name: Flutter doctor
        script: flutter doctor -v

      - name: Get Flutter packages
        script: flutter pub get

      # نبني .app فقط بدون توقيع (ما يحتاج Development Team)
      - name: Build iOS .app (unsigned)
        script: flutter build ios --release --no-codesign

    # نطلع Runner.app كأرتيفاكت، وإنت تكبسه يدويًا لاحقًا
    artifacts:
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
