workflows:
  ios-release-app-only:
    name: iOS Release - APP only (no signing)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: 3.35.4   # Dart >= 3.5.3
      xcode: latest

    scripts:
      - name: Doctor & deps
        script: |
          set -e
          flutter doctor -v
          flutter clean
          flutter pub get
          flutter precache --ios

      # لو ماكو iOS، نولده رسميًا
      - name: Ensure iOS platform (auto-create if missing)
        script: |
          set -e
          if [ ! -f ios/Podfile ]; then
            echo "No Podfile found. Recreating iOS platform..."
            rm -rf ios
            flutter create --platforms=ios .
          fi
          ls -la ios || true

      # ✅ هنا نعدّل Podfile: منصة iOS = 13.0 + use_frameworks static
      - name: Patch Podfile (platform 13 + use_frameworks static)
        script: |
          set -e
          PODFILE="ios/Podfile"
          # اضبط platform :ios, '13.0'
          if grep -q "^platform :ios" "$PODFILE"; then
            # macOS sed
            sed -i '' -e "s/^platform :ios.*/platform :ios, '13.0'/" "$PODFILE"
          else
            # أدرج السطر في أعلى الملف
            printf "platform :ios, '13.0'\n%s" "$(cat "$PODFILE")" > "$PODFILE"
          fi
          # اضبط use_frameworks! :linkage => :static
          if grep -q "^use_frameworks!" "$PODFILE"; then
            sed -i '' -e "s/^use_frameworks!.*/use_frameworks! :linkage => :static/" "$PODFILE"
          else
            # أدرجه بعد أول سطر
            awk 'NR==1{print; print "use_frameworks! :linkage => :static"; next}1' "$PODFILE" > "$PODFILE.tmp" && mv "$PODFILE.tmp" "$PODFILE"
          fi
          echo "=== Podfile after patch ==="
          cat "$PODFILE"

      - name: Reinstall CocoaPods cleanly
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      # ⬇️ Build .app فقط بدون أي توقيع
      - name: Xcode build (no signing) → .app
        script: |
          set -e
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            IPHONEOS_DEPLOYMENT_TARGET=13.0
          echo "=== Build Products ==="
          ls -R build/Build/Products || true

    artifacts:
      - build/Build/Products/Release-iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
