workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean & get packages
        script: |
          flutter clean
          flutter pub get

      - name: Build IPA (no codesign) + verify output
        script: |
          flutter build ipa --release --no-codesign
          echo "=== FIND IPA ==="
          find build -maxdepth 5 -type f -name "*.ipa" -print || true
          echo "=== LIST build/ios/ipa ==="
          ls -la build/ios/ipa || true

    artifacts:
      - build/**/ipa/*.ipa
      - build/ios/archive/*.xcarchive
