name: var_app
description: "Var_IPTV"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase (Core + Auth + Firestore فقط)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # Device ID + Local cache
  device_info_plus: ^10.1.2
  shared_preferences: ^2.3.3

  # HTTP + تواريخ
  http: ^1.2.0
  intl: ^0.19.0

  # صور الشبكة مع كاش
  cached_network_image: ^3.3.1

  # فتح روابط خارجية
  url_launcher: ^6.3.0

  # معلومات الإصدار
  package_info_plus: ^8.0.0

  # فتح تطبيق أندرويد آخر (ما يأثر على iOS)
  android_intent_plus: ^5.2.0

  # صلاحيات (أبقِه إذا تحتاجه بمكان آخر)
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1   # توليد الأيقونة
  flutter_native_splash: ^2.4.0     # شاشة الإقلاع

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/bein/
    - assets/dazn/
    - assets/espn/
    - assets/mbc/
    - assets/roshnleague/
    - assets/premierleague/
    - assets/generalsports/
    - assets/SeriaA/   # تأكد من اسم المجلد فعليًا بدون مسافة

# إعدادات أيقونة التطبيق
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_monochrome: "assets/images/logo.png"

# إعدادات شاشة الإقلاع (Splash screen)
flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#000000"
